### ISSUE TITLE
wont run on server

### ISSUE THREAD

**Issue by powerBoat1** [YUNG-GANG/YUNGs-Better-Caves#160]
I cant get it to run on my server the mods wont load. I removed all other mods to eliminate that factor.

**Comment by powerBoat1** [comment]
[15:14:49] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.39-c1c5a946, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge]
[15:14:50] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 18.0.2.1 by Oracle Corporation
[15:14:50] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[15:14:50] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/memez/Desktop/server/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=SERVER
[15:14:51] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlserver' with arguments [--gameDir, .]
[15:14:52] [main/WARN] [mixin/]: Error loading class: java/util/Objects (java.lang.IllegalArgumentException: Class file major version 62 is not supported by active ASM (version 9.0 supports class version 61), reading java.util.Objects)
Exception in thread "main" [15:14:52] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1078]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[15:14:52] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1078]:       at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[15:14:52] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1078]:       at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[15:14:52] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1078]:       at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[15:14:52] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1078]:       at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[15:14:52] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1078]:       at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[15:14:52] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1078]:       at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:86)
[15:14:52] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1078]:       at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:83)
[15:14:52] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1078]:       at net.minecraftforge.server.ServerMain.main(ServerMain.java:80)
[15:14:52] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1087]: Caused by: java.lang.reflect.InvocationTargetException
[15:14:52] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1087]:       at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
[15:14:52] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1087]:       at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[15:14:52] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1087]:       at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:37)
[15:14:52] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1087]:       at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[15:14:52] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1087]:       ... 7 more
[15:14:52] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:658]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[15:14:52] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:658]:    at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
[15:14:52] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:658]:    at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
[15:14:52] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:658]:    at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
[15:14:52] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:658]:    at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
[15:14:52] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:658]:    at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[15:14:52] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:658]:    at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[15:14:52] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:658]:    at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[15:14:52] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:658]:    at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[15:14:52] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:658]:    at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[15:14:52] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:658]:    at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[15:14:52] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:658]:    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[15:14:52] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:658]:    at net.minecraftforge.registries.GameData.init(GameData.java:163)
[15:14:52] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:658]:    at net.minecraftforge.registries.GameData.<clinit>(GameData.java:118)
[15:14:52] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:658]:    at net.minecraft.util.registry.Registry.forge(Registry.java:347)
[15:14:52] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:658]:    at net.minecraft.util.registry.Registry.forge(Registry.java:331)
[15:14:52] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:658]:    at net.minecraft.util.registry.Registry.<clinit>(Registry.java:140)
[15:14:52] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:658]:    at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:41)
[15:14:52] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:658]:    at net.minecraft.server.Main.main(Main.java:138)
[15:14:52] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:658]:    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[15:14:52] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:658]:    ... 10 more
[15:14:52] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:681]: Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: java.util.Objects
[15:14:52] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:681]:    at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:754)
[15:14:52] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:681]:    at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:739)
[15:14:52] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:681]:    at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:310)
[15:14:52] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:681]:    at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:280)
[15:14:52] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:681]:    at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1288)
[15:14:52] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:681]:    at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292)
[15:14:52] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:681]:    at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
[15:14:52] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:681]:    at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
[15:14:52] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:681]:    at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[15:14:52] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:681]:    ... 28 more

**Comment by yungnickyoung** [comment]
Looks like you're using Java 18 on MC 1.16.5. I think you should try downgrading to Java 8 instead.
